-- MySQL Script generated by MySQL Workbench
-- Sun Jul  7 13:27:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shepherddbtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shepherddbtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shepherddbtest` DEFAULT CHARACTER SET utf8 ;
USE `shepherddbtest` ;

-- -----------------------------------------------------
-- Table `shepherddbtest`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shepherddbtest`.`user` ;

CREATE TABLE IF NOT EXISTS `shepherddbtest`.`user` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `SeenTutorial` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shepherddbtest`.`sheep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shepherddbtest`.`sheep` ;

CREATE TABLE IF NOT EXISTS `shepherddbtest`.`sheep` (
  `SheepId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Purpose` VARCHAR(100) NOT NULL,
  `Personality` VARCHAR(20) NOT NULL,
  `Age` INT NOT NULL DEFAULT 1,
  `Skin` VARCHAR(20) NOT NULL,
  `FrequencyInDays` INT NOT NULL,
  `Status` VARCHAR(15) NOT NULL DEFAULT 'active',
  `Health` INT NOT NULL,
  `DateCreated` DATE NOT NULL DEFAULT (CURDATE()),
  `DateLastFed` DATE NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`SheepId`),
  INDEX `fk_sheep_user_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_sheep_user`
    FOREIGN KEY (`UserId`)
    REFERENCES `shepherddbtest`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
